language: java

addons:
  postgresql: 9.6
  apt:
    packages:
    - graphviz

services:
  - mysql
  - docker

env:
  global:
  - BASEURL=https://archive.apache.org/dist/maven/maven-3/VERSION/binaries/apache-maven-VERSION-bin.zip
  - FILE=apache-maven-VERSION-bin.zip
  - DIR=apache-maven-VERSION
  - VERSION=3.6.3

os:
- linux

jdk:
- openjdk8
- openjdk11

matrix:
  fast_finish: true
  include:
  # additional builds
  - os: linux
    jdk: openjdk8
    env: VERSION=3.3.9
  - os: linux
    jdk: openjdk8
    env: VERSION=3.5.4
  - os: linux
    jdk: openjdk8
    env: VERSION=3.6.3

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
         wget --no-check-certificate $(echo -n $BASEURL | sed -e 's#VERSION#'$VERSION'#g');
         unzip -qq $(echo -n $FILE | sed -e 's#VERSION#'$VERSION'#');
         export M2_HOME=$PWD/$(echo -n $DIR | sed -e 's#VERSION#'$VERSION'#');
         export PATH=$M2_HOME/bin:$PATH;
    fi
  - echo $VERSION
  - echo $M2_HOME
  - sh ".travis/start-oracle.sh"
  - docker pull mcr.microsoft.com/mssql/server:2017-latest
  - docker run -v "$(pwd)"/:/checkout  -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password12!' -p 1433:1433 --name sql1 -d mcr.microsoft.com/mssql/server:2017-latest
  - docker ps -a

install:
  - mvn install -Dmaven.test.skip=true -B -V -fae -q

before_script:
  - psql -c 'create database test;' -U postgres
  - psql -U postgres -d test -f ./src/test/resources/sql/pgsql.sql
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql test < ./src/test/resources/sql/mysql.sql
  #- sqlcmd -S (local)\sql1 -U sa -P Password12! -Q "CREATE DATABASE test" -d "master"
  - docker exec -it sql1 /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Password12!' -Q 'CREATE DATABASE test' -d "master"
  #- sqlcmd -S (local)\sql1 -U sa -P Password12! -d "test" -i .\src\test\resources\sql\mssql.sql
  - docker exec -it sql1 /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Password12!' -d 'test' -i /checkout/src/test/resources/sql/mssql.sql
  - docker exec -i schemaspy /opt/oracle/product/18c/dbhomeXE/bin/sqlplus -l system/oracle@//localhost:1521/XE < .travis/create_oracle_user.sql
  - docker exec -i schemaspy /opt/oracle/product/18c/dbhomeXE/bin/sqlplus -l schemaspy/schemaspy@//localhost:1521/XE < ./src/test/resources/sql/oracle.sql

script:
  - mvn -e -B -fae -Ptravis clean test -Dorg.slf4j.simpleLogger.showDateTime=true -Dfailsafe.useFile=false
  - if [ "$TRAVIS_JDK_VERSION" == "openjdk8" ] && [ "$VERSION" == "3.6.3" ]; then
      mvn javadoc:javadoc;
    fi
  - if [ "$TRAVIS_JDK_VERSION" == "openjdk8" ] && [ "$VERSION" == "3.6.3" ]; then
      mvn javadoc:test-javadoc;
    fi

after_success:
  # generate code coverage report, just for oraclejdk8 and latest maven
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$VERSION" == "3.6.3" ] &&
       [ "$TRAVIS_JDK_VERSION" == "openjdk8" ]; then
         mvn -B -e -fae -Ptravis jacoco:report coveralls:report;
    fi

cache:
  directories:
  - $HOME/.m2
